version: '3'
services:
  jupyter-tutorial:
    build: .
    container_name: jupyter.local-m10
    user: root
    environment:
      - GRANT_SUDO=yes
      - aws_access_key_id='anything'
      - aws_secret_access_key='anything'
      - region_name='ap-northeast-1'
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''

  mariadb:
    image: mariadb
    container_name: cc104.rds.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ggboy
    volumes:
    - ./data_maria/:/var/lib/mysql
 
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ggboy
    volumes:
      - ./data_mysql/:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  dynamodb:
    build: ./dynamodbdockerfile/
    container_name: cc104.dynamodb.local
    volumes:
      - ./data_dynamo:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath ./data
